---
- name: API Driven Base64 to Zip (Custom Base Directory)
  hosts: all
  become: true
  gather_facts: false
  vars:
    # 1. กำหนด Base Directory (เปลี่ยนที่นี่ที่เดียว)
    base_dir: "/opt/apps/my_project"
    
    # 2. รับค่าจาก extra_vars
    zip_name: "{{ zip_name | default('ORG_26_001') }}"
    zip_base64: "{{ zip_content_from_api | default('') }}"
    
    # 3. กำหนด Path ต่างๆ โดยอิงจาก base_dir
    extract_path: "{{ base_dir }}/{{ zip_name }}"
    temp_zip: "{{ base_dir }}/{{ zip_name }}.zip"
    temp_b64: "{{ base_dir }}/{{ zip_name }}.base64"

  tasks:
    - name: "1. Ensure Base and Extraction directories exist"
      # สร้าง Base Directory และ Folder ปลายทางไปพร้อมกัน
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root # เปลี่ยนเป็น user ที่คุณต้องการได้
        group: root
      with_items:
        - "{{ base_dir }}"
        - "{{ extract_path }}"

    - name: "2. Write Base64 string to a temp file in Base Directory"
      copy:
        content: "{{ zip_base64 | trim }}"
        dest: "{{ temp_b64 }}"
        mode: '0644'
      when: zip_base64 | trim != ""

    - name: "3. Decode Base64 to Zip file"
      shell: "base64 -d {{ temp_b64 }} > {{ temp_zip }}"
      args:
        creates: "{{ temp_zip }}"

   # - name: "4. Extract Zip file to specific directory"
    #  unarchive:
     #   src: "{{ temp_zip }}"
     #   dest: "{{ extract_path }}"
     #   remote_src: yes
    #  register: extract_res
    #  ignore_errors: yes

   # - name: "5. Fallback: Extract using unzip command"
   #   shell: "unzip -o {{ temp_zip }} -d {{ extract_path }}"
  #    when: extract_res.failed

    - name: "6. Cleanup temporary files"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ temp_b64 }}"
        - "{{ temp_zip }}"
