---
- name: Test Base64 to Zip
  hosts: localhost
  connection: local
  vars:
    # String ที่ผมเจนให้ด้านบน
    zip_base64: "UEsDBAoAAAAAAIdYVlkAAAAAAAAAAAAAAAAADQAAYWhlbGxvd29ybGQudHRoZWxsbyB3b3JsZApQSwECPwAUAAoAAAAAAIdYVlkAAAAAAAAAAAAAAAAADQAkAAAAAAAAACAAAAAAAAAAYWhlbGxvd29ybGQudHAKAAAAAAIAAAAAAAAATQIAAAAAAAA="

  tasks:
    - name: "1. สร้างไฟล์ ZIP จาก Base64"
      copy:
        content: "{{ zip_base64 | b64decode }}"
        dest: "/tmp/test_hello.zip"

    - name: "2. สร้าง Folder สำหรับแตกไฟล์"
      file:
        path: "/tmp/hello_extracted"
        state: directory

    - name: "3. แตกไฟล์ ZIP"
      unarchive:
        src: "/tmp/test_hello.zip"
        dest: "/tmp/hello_extracted"
        remote_src: yes

    - name: "4. ตรวจสอบเนื้อหาในไฟล์ที่แตกออกมา"
      command: cat /tmp/hello_extracted/helloworld.txt
      register: file_content

    - name: "5. แสดงผลข้อความในไฟล์"
      debug:
        msg: "Content in file is: {{ file_content.stdout }}"
