---
- name: API Driven Base64 to Zip
  hosts: localhost
  connection: local
  # เรากำหนดค่าเริ่มต้นเป็น null ไว้ เพื่อป้องกัน error ถ้าไม่ได้ส่งค่ามา
  vars:
    zip_base64: "{{ zip_content_from_api | default('') }}"

  tasks:
    - name: "Check if base64 string is provided"
      fail:
        msg: "No base64 string provided in 'zip_content_from_api'"
      when: zip_base64 == ""

    - name: "Decode Base64 and save as .zip"
      copy:
        content: "{{ zip_base64 | b64decode }}"
        dest: "/tmp/api_output.zip"

    - name: "Extract Zip"
      unarchive:
        src: "/tmp/api_output.zip"
        dest: "/tmp/"
        remote_src: yes
