---
- name: API Driven Base64 to Zip (Fixed Path)
  hosts: all
  become: true
  gather_facts: false
  vars:
    base_dir: "/opt/apps/my_project"
    zip_name: "{{ zip_name | default('ORG_26_001') }}"
    zip_base64: "{{ zip_content_from_api | default('') }}"
    
    # แก้ไขจุดนี้: เชื่อม String ด้วยเครื่องหมาย / ให้ชัดเจน
    temp_b64: "{{ base_dir }}/{{ zip_name }}.base64"
    final_zip: "{{ base_dir }}/{{ zip_name }}.zip"

  tasks:
    - name: "1. Ensure Base Directory exists"
      file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'

    - name: "2. Write Base64 string to a temp file"
      copy:
        content: "{{ zip_base64 | trim }}"
        dest: "{{ temp_b64 }}"
        mode: '0600'
      when: zip_base64 | trim != ""

    - name: "3. Decode Base64 to Zip file"
      # ใช้เครื่องหมาย " " ครอบ Path เพื่อป้องกันกรณีชื่อไฟล์มีช่องว่าง
      shell: "base64 -d \"{{ temp_b64 }}\" > \"{{ final_zip }}\""
      
    - name: "4. Cleanup temporary file"
      file:
        path: "{{ temp_b64 }}"
        state: absent

    - name: "5. Verify result"
      command: "ls -lh {{ final_zip }}"
      register: final_check

    - debug:
        msg: "File saved at: {{ final_check.stdout }}"
